"""Git and PR enrichment for changelog generation.

This module handles:
- Fetching commit history from git
- Classifying contributors (Human, Bot, AI/Agent)
- Extracting PR numbers from merge commits
- Classifying change types from conventional commits
- Area classification from changed files
"""

from __future__ import annotations

import datetime as _dt
import re
import subprocess
from typing import List, Optional, Tuple

from tools.chngbrgr.config import (
    AI_AGENT_PATTERNS,
    BOT_PATTERNS,
    CHANGE_TYPE_PREFIXES,
    CHANGELOG_ONLY_FILES,
    CONTRIBUTOR_AI,
    CONTRIBUTOR_BOT,
    CONTRIBUTOR_HUMAN,
    EXCLUDED_COMMIT_PATTERNS,
    PATH_BUCKETS,
    ROOT,
)
from tools.chngbrgr.models import CommitInfo


def validate_date_format(date_str: Optional[str]) -> Optional[str]:
    """Validate and normalize date string to YYYY-MM-DD format.

    Args:
        date_str: Date string to validate

    Returns:
        Validated date string in YYYY-MM-DD format, or None if invalid/empty

    Raises:
        ValueError: If date_str is not in valid YYYY-MM-DD format
    """
    if not date_str:
        return None

    # Strict regex validation for YYYY-MM-DD format
    if not re.match(r"^\d{4}-\d{2}-\d{2}$", date_str):
        raise ValueError(f"Invalid date format: {date_str!r}. Expected YYYY-MM-DD.")

    # Validate it's a real date
    try:
        _dt.datetime.strptime(date_str, "%Y-%m-%d")
    except ValueError as e:
        raise ValueError(f"Invalid date: {date_str!r}. {e}") from e

    return date_str


def classify_contributor_type(author: str, subject: str) -> str:
    """Classify contributor as Human, Bot, or AI/Agent.

    Args:
        author: Commit author name
        subject: Commit subject line

    Returns:
        CONTRIBUTOR_HUMAN, CONTRIBUTOR_BOT, or CONTRIBUTOR_AI
    """
    lower_author = author.lower()
    lower_subject = subject.lower()

    # Check for bot patterns in author name
    for pattern in BOT_PATTERNS:
        if pattern in lower_author:
            return CONTRIBUTOR_BOT

    # Check for AI/agent patterns in author name or subject
    for pattern in AI_AGENT_PATTERNS:
        if pattern in lower_author or pattern in lower_subject:
            return CONTRIBUTOR_AI

    # Check for common bot author name patterns
    if lower_author.endswith("[bot]") or lower_author.endswith("-bot"):
        return CONTRIBUTOR_BOT

    # Check for AI-assisted commit indicators in subject
    if any(marker in lower_subject for marker in ["co-authored-by: github copilot", "🤖", "generated by"]):
        return CONTRIBUTOR_AI

    return CONTRIBUTOR_HUMAN


def is_changelog_commit(subject: str, files: List[str]) -> bool:
    """Check if commit is a changelog-only update (should be excluded).

    Exclusion criteria:
    1. Subject matches known changelog-maintenance patterns
    2. Commit only touches CHANGELOG.md (self-referential)

    This prevents recursive changelog entries.
    Note: Bot/AI commits are NOT excluded here - they go in separate sections.

    Args:
        subject: Commit subject line
        files: List of files changed in the commit

    Returns:
        True if commit should be excluded from changelog
    """
    lower = subject.lower()

    # Check subject patterns for changelog-specific commits
    for pattern in EXCLUDED_COMMIT_PATTERNS:
        if pattern in lower:
            return True

    # Check if commit only touches changelog file(s) - self-referential
    if files and set(files) <= CHANGELOG_ONLY_FILES:
        return True

    # Empty commits (merge commits with no file changes recorded)
    if not files and not subject.strip():
        return True

    return False


def classify_change_type(subject: str) -> str:
    """Classify commit by conventional commit prefix.

    Args:
        subject: Commit subject line

    Returns:
        Change type string (Features, Fixes, etc.) or "Other"
    """
    lower = subject.lower()
    for prefix, change_type in CHANGE_TYPE_PREFIXES.items():
        if lower.startswith(f"{prefix}:") or lower.startswith(f"{prefix}("):
            return change_type
    return "Other"


def extract_pr_number(subject: str) -> Optional[int]:
    """Extract PR number from merge commit or squash-merge subject.

    Args:
        subject: Commit subject line

    Returns:
        PR number if found, None otherwise
    """
    # Merge pull request #123 from ...
    match = re.search(r"Merge pull request #(\d+)", subject)
    if match:
        return int(match.group(1))
    # Subject (#123) - squash merge format
    match = re.search(r"\(#(\d+)\)\s*$", subject)
    if match:
        return int(match.group(1))
    return None


def classify_areas(files: List[str]) -> List[str]:
    """Classify changed files into area buckets.

    Args:
        files: List of file paths changed

    Returns:
        Sorted list of area names
    """
    areas: set[str] = set()
    for file_path in files:
        matched = False
        for area, patterns in PATH_BUCKETS.items():
            for pattern in patterns:
                if pattern.startswith("*"):
                    if file_path.endswith(pattern[1:]):
                        areas.add(area)
                        matched = True
                        break
                elif file_path.startswith(pattern) or pattern in file_path:
                    areas.add(area)
                    matched = True
                    break
            if matched:
                break
        if not matched:
            areas.add("Other")
    return sorted(areas)


def get_commits_since(since_date: Optional[str]) -> List[CommitInfo]:
    """Get detailed commit info since a date.

    Args:
        since_date: Date string in YYYY-MM-DD format

    Returns:
        List of CommitInfo objects for non-merge commits since the date

    Raises:
        ValueError: If since_date is not in valid YYYY-MM-DD format
    """
    validated_date = validate_date_format(since_date)
    if not validated_date:
        return []

    cmd = [
        "git",
        "log",
        f"--since={validated_date}T00:00:00",
        "--pretty=format:%h|%s|%an",
        "--no-merges",
    ]
    # Security: since_date is validated via validate_date_format() to ensure YYYY-MM-DD format.
    # Using list form prevents shell injection.
    try:
        output = subprocess.check_output(cmd, cwd=ROOT, text=True, stderr=subprocess.DEVNULL)  # nosec B603
    except Exception:
        return []

    commits: List[CommitInfo] = []
    for line in output.splitlines():
        if not line.strip():
            continue
        parts = line.split("|", 2)
        if len(parts) < 3:
            continue
        sha, subject, author = parts

        # Get files changed by this commit
        try:
            files_output = subprocess.check_output(
                ["git", "diff-tree", "--no-commit-id", "--name-only", "-r", sha],
                cwd=ROOT,
                text=True,
                stderr=subprocess.DEVNULL,
            )  # nosec B603
            files = [f.strip() for f in files_output.splitlines() if f.strip()]
        except Exception:
            files = []

        # Skip changelog-only commits to prevent recursion
        if is_changelog_commit(subject, files):
            continue

        commits.append(
            CommitInfo(
                sha=sha,
                subject=subject,
                author=author,
                files=files,
                pr_number=extract_pr_number(subject),
                change_type=classify_change_type(subject),
                contributor_type=classify_contributor_type(author, subject),
            )
        )

    return commits


def is_excluded_pr(subject: str) -> bool:
    """Check if a PR merge commit should be excluded from changelog.

    Args:
        subject: Merge commit subject line

    Returns:
        True if PR should be excluded
    """
    lower = subject.lower()
    for pattern in EXCLUDED_COMMIT_PATTERNS:
        if pattern in lower:
            return True
    return False


def get_merge_prs_since(since_date: Optional[str]) -> List[Tuple[int, str]]:
    """Get merged PR numbers and titles from merge commits.

    Args:
        since_date: Date string in YYYY-MM-DD format

    Returns:
        List of (pr_number, title) tuples

    Raises:
        ValueError: If since_date is not in valid YYYY-MM-DD format
    """
    validated_date = validate_date_format(since_date)
    if not validated_date:
        return []

    cmd = [
        "git",
        "log",
        f"--since={validated_date}T00:00:00",
        "--merges",
        "--pretty=format:%s",
    ]
    # Security: since_date is validated via validate_date_format() to ensure YYYY-MM-DD format.
    try:
        output = subprocess.check_output(cmd, cwd=ROOT, text=True, stderr=subprocess.DEVNULL)  # nosec B603
    except Exception:
        return []

    prs: List[Tuple[int, str]] = []
    for line in output.splitlines():
        if not line.strip():
            continue
        # Skip excluded PRs (changelog updates, bots, etc.)
        if is_excluded_pr(line):
            continue
        pr_num = extract_pr_number(line)
        if pr_num:
            # Extract branch name as proxy for title
            match = re.search(r"from \S+/(.+)$", line)
            title = match.group(1).replace("-", " ").replace("_", " ") if match else line
            prs.append((pr_num, title))

    return prs
